name = "Arch"
license = "MIT"
licenselink = "https://github.com/snlab-freedom/hugo-theme-cooler/blob/master/LICENSE"
description = "Hugo Theme Cooler"
homepage = "https://snlab-freedom.github.io/hugo-theme-cooler"
tags = ["blog"]
features = ["arch linux","bootstrap", "talaria"]
min_version=0.15

[author]
    name = "SNLab.Org"
    homepage = "https://snlab-freedom.github.io"

[original]
    name = "syui"
    homepage = "https://syui.github.io"
