baseurl = "https://snlab-freedom.github.io/"
languageCode = "en-us"
title = "SNLab Freedom Zone"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per site
paginate = 10
theme = "hugo-theme-cooler"

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you're
    location = ""
    site_description = ""
    organization = "SNLab.Freedom"
    organization_url = "https://github.com/snlab_freedom"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [cooler](https://gitlab.com/snlab-freedom/hugo-theme-cooler)."

    # Format dates with Go's time formating
    date_format = "2006-01-02"

    # Meta data for your website
    title = "SNLab"
    subtitle = "Freedom"

# Create custom menu entries by defining a name and a url for
# them. You can set weight to decide the index of each item.
[[menu.main]]
    name  = "Home"
    identifier = "home"
    url   = "/"
    weight = 0

[[menu.main]]
    name   = "Posts"
    url    = "/posts"
    identifier = "posts"
    weight = 100

[[menu.main]]
    name = "Members"
    identifier = "members"
    url = "/members"
    weight = 150

[[menu.main]]
    name  = "Publications"
    url   = "/publications"
    identifier = "publications"
    weight = 200

[[menu.main]]
    name  = "Projects"
    identifier = "projects"
    weight = 300

# You can set the nested submenu by indicate the parent.
[[menu.main]]
    name = "Project List"
    url = "/projects"
    parent = "projects"
    weight = 300

[[menu.main]]
    pre = "<li role ='separator' class='divider'></li>"
    name = "Project1"
    url = "/projects/project1/"
    parent = "projects"
    weight = 310

[[menu.main]]
    name = "Project2"
    url = "/projects/project2/"
    parent = "projects"
    weight = 320

[[menu.main]]
    name = "Project3"
    url = "/projects/project3/"
    parent = "projects"
    weight = 330

[[menu.main]]
    name = "Project4"
    url = "/projects/project4/"
    parent = "projects"
    weight = 340

# Set a `pre` attribute for a submenu to display a divider.
[[menu.main]]
    pre = "<li role ='separator' class='divider'></li>"
    name = "Tutorials"
    parent = "projects"
    identifier = "tutorials"
    weight = 380

[[menu.main]]
    name = "Write your first project"
    url = "#"
    parent = "tutorials"

[[menu.main]]
    name = "Test and deploy your projects"
    url = "#"
    parent = "tutorials"

[[menu.main]]
    name = "Demos"
    parent = "projects"
    identifier = "demos"
    weight = 390

[[menu.main]]
    name = "Video demo"
    url = "/videos"
    parent = "demos"

[[menu.main]]
    name = "Live demo"
    url = "/demos"
    parent = "demos"

[[menu.main]]
    before = false
    name  = "About"
    url   = "/about"
    weight = 400

# Sidebars content
[[params.widget.documentation]]
    name = "Demos"
    url = "/demos"
[[params.widget.documentation]]
    name = "Tutorials"
    url = "/tutorials"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = ""

# Article First Content
[params.article_first]
    title = "An example title"
    body = [
    "An example body"
    ]
    rss_show = true

[[params.members]]
    position = "Director"
[[params.members]]
    position = "Faculty"
[[params.members]]
    position = "Postdocs"
[[params.members]]
    position = "Graduate"
[[params.members]]
    position = "Undergraduate"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "example"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = "token"
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "example"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = "example"
    facebook        = "example"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "example"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
    download = false
    documentation = true
