baseurl = "https://snlab-freedom.github.io/"
languageCode = "en-us"
title = "SNLab Freedom Zone"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per site
paginate = 10
theme = "hugo-theme-cooler"

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you're
    location = ""
    site_description = ""
    organization = "SNLab.Freedom"
    organization_url = "https://github.com/snlab_freedom"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [cooler](https://gitlab.com/snlab-freedom/hugo-theme-cooler)."

    # Format dates with Go's time formating
    date_format = "2006-01-02"

# Create custom menu entries by defining a name and a url for
# them. You can set weight to decide the index of each item.
[[menu.main]]
    before = true
    name  = "Home"
    identifier = "home"
    url   = "/"
    weight = 0

[[menu.main]]
    before = false
    name   = "Posts"
    url    = "post/"
    identifier = "post"
    weight = 100

[[menu.main]]
    before = false
    name  = "Publications"
    url   = "publications/"
    identifier = "publications"
    weight = 200

[[menu.main]]
    before = false
    name  = "Projects"
    identifier = "projects"
    weight = 300

# You can set the nested submenu by indicate the parent.
[[menu.main]]
    name = "Project1"
    url = "#"
    parent = "projects"
    weight = 300

[[menu.main]]
    name = "Project2"
    url = "#"
    parent = "projects"
    weight = 310

[[menu.main]]
    name = "Project3"
    url = "#"
    parent = "projects"
    weight = 320

[[menu.main]]
    name = "Project4"
    url = "#"
    parent = "projects"
    weight = 330

# Set a `pre` attribute for a submenu to display a divider.
[[menu.main]]
    pre = "<li role ='separator' class='divider'></li>"
    name = "Tutorials"
    parent = "projects"
    identifier = "tutorials"
    weight = 340

[[menu.main]]
    name = "Write your first project"
    url = "#"
    parent = "tutorials"

[[menu.main]]
    name = "Test and deploy your projects"
    url = "#"
    parent = "tutorials"

[[menu.main]]
    name = "Demos"
    parent = "projects"
    identifier = "demos"
    weight = 350

[[menu.main]]
    name = "Video demo"
    url = "videos/"
    parent = "demos"

[[menu.main]]
    name = "Live demo"
    url = "demos/"
    parent = "demos"

[[menu.main]]
    before = false
    name  = "About"
    url   = "about/"
    weight = 400

# Sidebars content
[[params.widget.documentation]]
    name = "Wiki"
    url = "documentation/wiki/"
[[params.widget.documentation]]
    name = "Tutorial"
    url = "documentation/tutorial/"
[[params.widget.documentation]]
    name = "other doc"
    url = "#"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = ""

# Article First Content
[params.article_first]
    show = true
    title = "An example title"
    body = "An example body"
    rss_show = true

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
    download = false

